// Generated by CoffeeScript 1.9.0
var test;

test = (function() {
  function test() {}

  test.prototype.contructor = function() {
    return this.myprop = true;
  };

  test.prototype.method = function(a, b) {
    var value;
    value = null;
    return a + b;
  };

  test.prototype.method2 = function() {
    var arr, i, interpolation, item, _i, _j, _len;
    this.a = (function(_this) {
      return function() {
        return _this.a + 1;
      };
    })(this);
    arr = [];
    if (this.myprop === true) {
      alert(1);
    }
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      item = arr[_i];
      alert(item);
    }
    for (i = _j = 0; _j <= 10; i = ++_j) {
      alert(1);
    }
    switch (this.myprop) {
      case 1:
        alert(1);
        break;
      default:
        1;
    }
    return interpolation = this.myprop + " yo soy coffeee";
  };

  return test;

})();
