// Generated by CoffeeScript 1.9.0
'use strict';
var http;

http = require('http');

http.createServer(function(req, res) {
  res.writeHead(200, {
    'Content-Type': 'text-plain'
  });
  res.end('Hello World\n');
}).listen('1337', '127.0.0.1');

console.log('Server running http://127.0.0.1:1337/');
