// Generated by CoffeeScript 1.9.0
'use-strict';
var http, httpProxy, seaport;

http = require('http');

httpProxy = require('http-proxy');

seaport = require('seaport');

(function() {
  var argument, i, ports;
  argument = process.argv.splice(2);
  ports = seaport.connect('127.0.0.1', 9000);
  i = 0;
  ports.once('synced', function() {
    var proxy;
    proxy = httpProxy.createProxyServer();
    http.createServer(function(req, res) {
      var address, addresses, json, objTarget;
      addresses = ports.query('pi_server');
      if (addresses.length === 0) {
        res.writeHead(503, {
          'Content-Type': 'text/plain'
        });
        res.end('Service Unavailable');
        return;
      }
      address = addresses[i];
      if (address != null) {
        objTarget = {
          target: {
            host: address.host,
            port: address.port
          }
        };
        json = JSON.stringify(objTarget, true, 2);
        console.log("> Target: " + json);
        proxy.web(req, res, objTarget);
        i = (i + 1) % addresses.length;
      }
      res.end;
    }).listen(argument[0] || 8000);
    proxy.on('open', function(proxySocket) {
      console.log('> Proxy Open');
    });
    proxy.on('proxyReq', function(proxyReq, req, res, options) {
      console.log("> Start Req");
    });
    proxy.on('proxyRes', function(proxyRes, req, res) {
      console.log("> Start Res");
    });
    proxy.on('close', function(req, socket, head) {
      console.log('> Proxy Close');
    });
  });
  console.log("Server Running...");
})();
