// Generated by CoffeeScript 1.9.0
'use-strict';
var bouncy, http, seaport;

http = require('http');

seaport = require('seaport');

bouncy = require('bouncy');

(function() {
  var arg, i, server;
  arg = process.argv.splice(2);
  server = seaport.createServer();
  server.listen(9090);
  i = 0;
  bouncy(function(req, res, bounce) {
    var address, addresses;
    addresses = server.query('vivo_4g_exagerado@0.1.0');
    if (addresses.length > 0) {
      address = addresses[i];
      if (address != null) {
        console.log(address);
        i = (i + 1) % addresses.length;
        bounce(address);
      }
    } else {
      res.writeHead(503, {
        'Content-Type': 'text/plain'
      });
      res.end('Service Unavailable');
    }
  }).listen(arg[0] || 8000);
  console.log("Server Running...");
})();
