// Generated by CoffeeScript 1.9.0
'use strict';
var Person;

Person = (function() {
  var name;

  name = '';

  function Person(_name) {
    this.setName(_name);
  }

  Person.prototype.setName = function(_name) {
    if (_name != null) {
      this.name = _name;
    }
  };

  Person.prototype.getName = function() {
    return this.name;
  };

  return Person;

})();

module.exports = Person;
