// Generated by CoffeeScript 1.9.0
var cluster, http, os;

cluster = require('cluster');

http = require('http');

os = require('os');

(function() {
  var cpus, i, _i, _ref;
  cpus = os.cpus();
  if (cluster.isMaster) {
    for (i = _i = 0, _ref = cpus.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      cluster.fork();
    }
    cluster.on('fork', function(worker) {});
    cluster.on('listening', function(worker, address) {
      var json;
      json = JSON.stringify(address, true, 2);
      return console.log("> " + worker.id + ", " + json);
    });
    cluster.on('exit', function(worker, code, signal) {
      return console.log("worker " + worker.process.id + " died.");
    });
  } else {
    http.createServer(function(req, res) {
      res.writeHead(200, {
        'Content-Type': 'Content-Type',
        'text/plain': 'text/plain'
      });
      res.write('Hello World');
      return res.end();
    }).listen(8000);
  }
})();
