// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("App")]
[assembly: AssemblyDescriptionAttribute("App")]
[assembly: AssemblyProductAttribute("App")]
[assembly: GuidAttribute("a15a723f-7c82-4e40-b7ec-c5003a5310d5")]
[assembly: AssemblyVersionAttribute("0.1.1")]
[assembly: AssemblyFileVersionAttribute("0.1.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1";
        internal const string InformationalVersion = "0.1.1";
    }
}
