// Generated by CoffeeScript 1.9.0
'use strict';
var net, server;

net = require('net');

server = net.createServer(function(socket) {
  socket.write('Echo server\r\n');
  socket.pipe(socket);
});

server.listen('1337', '127.0.0.1');
