// Generated by CoffeeScript 1.9.0
'use-strict';
var http, httpProxy;

http = require('http');

httpProxy = require('http-proxy');

(function() {
  var addresses, argument, i, proxy;
  argument = process.argv.splice(2);
  i = 0;
  addresses = [
    {
      host: 'http://127.0.0.1',
      port: '8001'
    }, {
      host: 'http://127.0.0.1',
      port: '8002'
    }, {
      host: 'http://127.0.0.1',
      port: '8003'
    }
  ];
  proxy = httpProxy.createProxyServer();
  http.createServer(function(req, res) {
    var address, target;
    address = addresses[i];
    console.log(address);
    if (address) {
      target = {
        target: address.host + ":" + address.port
      };
      proxy.web(req, res, target);
    }
    i = (i + 1) % addresses.length;
  }).listen(argument[0] || 8000);
  proxy.on('open', function(proxySocket) {
    console.log('Proxy Open');
    console.log(proxySocket);
  });
  proxy.on('proxyRes', function(proxyRes, req, res) {
    var json;
    json = JSON.stringify(proxyRes.headers, true, 2);
    console.log(json);
  });
  proxy.on('close', function(req, socket, head) {
    console.log('Proxy Close');
  });
  console.log("Server Running...");
})();
