// Generated by CoffeeScript 1.9.0
'use-strict';
var http;

http = require('http');

(function() {
  var args, estimatePi, server;
  args = process.argv.splice(2);
  estimatePi = function() {
    var calc, i, inside, n, x, y, _i;
    n = 10000000;
    inside = 0;
    for (i = _i = 0; 0 <= n ? _i <= n : _i >= n; i = 0 <= n ? ++_i : --_i) {
      x = Math.random();
      y = Math.random();
      calc = Math.sqrt(x * x + y * y);
      if (calc <= 1) {
        inside++;
      }
    }
    return 4 * inside / n;
  };
  server = http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    res.end("Pi:" + (estimatePi()));
  });
  server.listen(args[0] || 8000);
  console.log("Server Running...");
})();
